answer_user_task:
  description: >
    Answer this user question: {user_query}. And provide information on demand.
  expected_output: Provide a detailed response to the user query.
    Offer additional information or context as needed.
    Be prepared to answer follow-up questions or provide further assistance.

converse_user_task:
  description: >
    Consider this user message: {user_message} and this short summary of recent chats: {recent_chats_summary}. Engage in a casual conversation with the user.
  expected_output:
    Respond to the user's messages in a friendly and engaging manner.
    Maintain a conversational tone and flow throughout the interaction.
    Be prepared to discuss a variety of topics and respond to user input accordingly.

ask_user_question_task:
  description: >
    Ask the user a question related to the conversation. The question should be engaging and relevant to the ongoing discussion.
  expected_output:
    Pose a thought-provoking question that encourages the user to share their thoughts or opinions.
    Ensure that the question is related to the current topic of conversation.
    Be prepared to respond to the user's answer and continue the discussion.

translate_message_task:
  description: >
    Translate this message from {source_language} to {target_language}. Message : {message}
  expected_output:
    Provide an accurate translation of the message from the source language to the target language.
    Ensure that the translated message conveys the original meaning and intent effectively.
    Be prepared to answer questions or provide additional context if needed.
